"""Backward-compatibility module forwarding to backend.core.config.settings"""
from backend.core.config import settings

PRIMARY_LLM_PROVIDER = settings.PRIMARY_LLM_PROVIDER
SECONDARY_LLM_PROVIDER = settings.SECONDARY_LLM_PROVIDER
FALLBACK_LLM_PROVIDER = settings.FALLBACK_LLM_PROVIDER

GEMINI_API_KEY = settings.GEMINI_API_KEY
GROQ_API_KEY = settings.GROQ_API_KEY
OPENROUTER_API_KEY = settings.OPENROUTER_API_KEY

RSI_PERIOD = settings.RSI_PERIOD
MACD_FAST = settings.MACD_FAST
MACD_SLOW = settings.MACD_SLOW
MACD_SIGNAL = settings.MACD_SIGNAL
SMA_SHORT = settings.SMA_SHORT
SMA_MEDIUM = settings.SMA_MEDIUM
SMA_LONG = settings.SMA_LONG

HIGH_CONCENTRATION_THRESHOLD = settings.HIGH_CONCENTRATION_THRESHOLD
VERY_HIGH_CONCENTRATION_THRESHOLD = settings.VERY_HIGH_CONCENTRATION_THRESHOLD
BANNED_PHRASES = settings.BANNED_PHRASES
